workflows:
  android-debug:
    name: Tsega Android Debug
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.22.3
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.pub-cache
    scripts:
      - name: Get packages
        script: flutter packages pub get
      - name: Build APK
        script: flutter build apk --debug --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
